data:
  features:
  - segVal
  - minor_cn
  - intersect_ratio
  - purity
  - ploidy
  - AScore
  - pLOH
  - cna_burden
  - CN1
  - CN2
  - CN3
  - CN4
  - CN5
  - CN6
  - CN7
  - CN8
  - CN9
  - CN10
  - CN11
  - CN12
  - CN13
  - CN14
  - CN15
  - CN16
  - CN17
  - CN18
  - CN19
  - age
  - gender
  - type_BLCA
  - type_BRCA
  - type_CESC
  - type_COAD
  - type_DLBC
  - type_ESCA
  - type_GBM
  - type_HNSC
  - type_KICH
  - type_KIRC
  - type_KIRP
  - type_LGG
  - type_LIHC
  - type_LUAD
  - type_LUSC
  - type_OV
  - type_PRAD
  - type_READ
  - type_SARC
  - type_SKCM
  - type_STAD
  - type_THCA
  - type_UCEC
  - type_UVM
  - freq_Linear
  - freq_BFB
  - freq_Circular
  - freq_HR
  gene_id: gene_id
  sample_id: sample
  target: y
  missing_value_strategy:
    age: mean
training:
  seed: 2026
  batch_size: 4096
  epochs: 150
  early_stopping:
    patience: 50
    min_delta: 0.001
model:
  type: XGBoost
  variant: XGBNew
  params:
    eta: 0.05
    max_depth: 6
    gamma: 3
    subsample: 0.8
    max_delta_step: 1
    min_child_weight: 2
    alpha: 0.1
    lambda: 2
    objective: binary:logistic
    eval_metric: aucpr
    tree_method: hist
    device: cuda
features:
  engineering:
  - cn_imbalance
  - allele_imbalance
  - cna_burden_adj
  - ascore_adj
  - has_circular
  - has_bfb
  - has_hr
  - amplicon_type_count
  - cn_sig_diversity
  - max_cn_sig
  - purity_x_ploidy
  - has_loh
