data:
  features:
  - segVal
  - minor_cn
  - intersect_ratio
  - purity
  - ploidy
  - AScore
  - pLOH
  - cna_burden
  - CN1
  - CN2
  - CN3
  - CN4
  - CN5
  - CN6
  - CN7
  - CN8
  - CN9
  - CN10
  - CN11
  - CN12
  - CN13
  - CN14
  - CN15
  - CN16
  - CN17
  - CN18
  - CN19
  - age
  - gender
  - type_BLCA
  - type_BRCA
  - type_CESC
  - type_COAD
  - type_DLBC
  - type_ESCA
  - type_GBM
  - type_HNSC
  - type_KICH
  - type_KIRC
  - type_KIRP
  - type_LGG
  - type_LIHC
  - type_LUAD
  - type_LUSC
  - type_OV
  - type_PRAD
  - type_READ
  - type_SARC
  - type_SKCM
  - type_STAD
  - type_THCA
  - type_UCEC
  - type_UVM
  - freq_Linear
  - freq_BFB
  - freq_Circular
  - freq_HR
  gene_id: gene_id
  sample_id: sample
  target: y
  missing_value_strategy:
    age: mean
model:
  type: XGBoost
  variant: XGB11
  params:
    alpha: 0
    booster: gbtree
    device: cuda
    eta: 0.1
    eval_metric: aucpr
    gamma: 10
    lambda: 1
    max_delta_step: 0
    max_depth: 4
    min_child_weight: 1
    objective: binary:logistic
    random_state: 2026
    subsample: 0.6
    tree_method: hist
  features:
    core_11:
    - segVal
    - minor_cn
    - purity
    - ploidy
    - AScore
    - pLOH
    - cna_burden
    - freq_Linear
    - freq_BFB
    - freq_Circular
    - freq_HR
training:
  batch_size: 4096
  early_stopping:
    min_delta: 0.001
    patience: 50
  epochs: 200
  seed: 2026
