data:
  features:
  - segVal
  - minor_cn
  - intersect_ratio
  - purity
  - ploidy
  - AScore
  - pLOH
  - cna_burden
  - CN1
  - CN2
  - CN3
  - CN4
  - CN5
  - CN6
  - CN7
  - CN8
  - CN9
  - CN10
  - CN11
  - CN12
  - CN13
  - CN14
  - CN15
  - CN16
  - CN17
  - CN18
  - CN19
  - age
  - gender
  - type_BLCA
  - type_BRCA
  - type_CESC
  - type_COAD
  - type_DLBC
  - type_ESCA
  - type_GBM
  - type_HNSC
  - type_KICH
  - type_KIRC
  - type_KIRP
  - type_LGG
  - type_LIHC
  - type_LUAD
  - type_LUSC
  - type_OV
  - type_PRAD
  - type_READ
  - type_SARC
  - type_SKCM
  - type_STAD
  - type_THCA
  - type_UCEC
  - type_UVM
  - freq_Linear
  - freq_BFB
  - freq_Circular
  - freq_HR
  gene_id: gene_id
  sample_id: sample
  target: y
  missing_value_strategy:
    age: mean
training:
  seed: 2026
  batch_size: 4096
  epochs: 150
  early_stopping:
    patience: 50
    min_delta: 0.001
prediction:
  threshold: 0.5
model:
  type: NeuralNetwork
  variant: Transformer
  architecture:
    input_dim: 57
    hidden_dim: 128
    num_heads: 4
    num_layers: 3
    dropout: 0.3
    classifier:
    - input_dim: 128
      output_dim: 64
      activation: GELU
      dropout: 0.3
    - input_dim: 64
      output_dim: 1
      activation: null
  optimizer:
    type: AdamW
    lr: 0.001
    weight_decay: 0.01
  loss_function:
    type: BCEWithLogitsLoss
    pos_weight: 10.0
  scheduler:
    type: ReduceLROnPlateau
    patience: 10
